name: Publish npm
inputs:
  npm-token:
    required: true
    type: string
  github-token:
    required: true
    type: string
runs:
  using: composite
  steps:

    - name: create and publish versions
      uses: changesets/action@v1
      with:
        version: pnpm ci:version
        commit: "chore: update versions"
        title: "chore: update versions"
        publish: pnpm ci:publish
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
