name: CI
 
on:
  push:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  BUILD_VERSION: 1.${{ github.run_id }}.${{ github.run_number }}

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  pull-requests: write
 
jobs:
  build:
    timeout-minutes: 90
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Setup corepack
        run: corepack enable

      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: |
          git config --global user.email "github-action@example.com"
          git config --global user.name "Github Bot"

      - name: Install dependencies
        run: pnpm install 

      - run: echo $BUILD_VERSION

      - name: create and publish versions
        uses: changesets/action@v1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm publish:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Build ios dev
      #   run: pnpm eas build --profile development --platform ios --non-interactive
      #   working-directory: packages/app
      #   env:
      #     EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}
      #
      # - name: Build ios preview
      #   working-directory: packages/app
      #   run: pnpm eas build --profile preview --platform ios --non-interactive
      #   env:
      #     EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Build ios production 
        working-directory: packages/app
        run: pnpm eas build --profile production --platform ios --non-interactive
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Submit iOS
        run: eas submit --platform ios --non-interactive --latest
        working-directory: packages/app
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

